<?php

namespace MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRouteCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRouteCardRepository extends EntityRepository
{
    public function getRawCardSumByIds()
    {
        $query =  $this->getEntityManager()
            ->createQuery("SELECT pre.id, st.hourSalary
                          FROM MainBundle:ProductRouteCard pre
                          index BY pre.id
                           JOIN pre.profession pf
                           JOIN pre.professionCategory pc
                           JOIN pf.salariesType st
                           JOIN pc.salariesType st1
                           WHERE st = st1

                          ");

        return $query->getResult();
    }
}
